name: Do Stuff and Push Back

on:
  workflow_dispatch: # manual trigger (good for testing)

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      
      - name: Configure Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          
      # Step 3. (Optional) Do your custom clone logic
      # If you want to re-clone with special flags:
      - name: Custom clone
        run: |
          curl -L https://github.com/abdullahalternative/openitools-ipcc/raw/refs/heads/main/bare-clone.sh | bash

      - name: run
        run: |
          cd openitools-ipcc
          pip install -r requirements.txt 
          python src/main.py -g --min-firmware 10
